### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by prayagpawar** [dingjiansw101/AerialDetection#103]
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
2022-11-21 16:08:57,399 - INFO - Start running, host: pdrl@pdrl, work_dir: /home/pdrl/aerialdetection/AerialDetection/work_dirs/faster_rcnn_RoITrans_r50_fpn_1x_dota
2022-11-21 16:08:57,399 - INFO - workflow: [('train', 1)], max: 12 epochs
Traceback (most recent call last):
  File "tools/train.py", line 95, in <module>
    main()
  File "tools/train.py", line 91, in main
    logger=logger)
  File "/home/pdrl/aerialdetection/AerialDetection/mmdet/apis/train.py", line 61, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/home/pdrl/aerialdetection/AerialDetection/mmdet/apis/train.py", line 197, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/pdrl/anaconda3/envs/AerialDetection/lib/python3.7/site-packages/mmcv/runner/runner.py", line 359, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/pdrl/anaconda3/envs/AerialDetection/lib/python3.7/site-packages/mmcv/runner/runner.py", line 259, in train
    for i, data_batch in enumerate(data_loader):
  File "/home/pdrl/anaconda3/envs/AerialDetection/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 278, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "/home/pdrl/anaconda3/envs/AerialDetection/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 709, in __init__
    self._try_put_index()
  File "/home/pdrl/anaconda3/envs/AerialDetection/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 826, in _try_put_index
    index = self._next_index()
  File "/home/pdrl/anaconda3/envs/AerialDetection/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 318, in _next_index
    return next(self.sampler_iter)  # may raise StopIteration
  File "/home/pdrl/anaconda3/envs/AerialDetection/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 200, in __iter__
    for idx in self.sampler:
  File "/home/pdrl/aerialdetection/AerialDetection/mmdet/datasets/loader/sampler.py", line 63, in __iter__
    indices = np.concatenate(indices)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate
when i run train.py i get this

**Comment by 622tongtong** [comment]
I am experiencing the same problem, how did you resolve this issue?

**Comment by dingjiansw101** [comment]
I did not meet this error before. Did you install the code with the correct lib version?
