### ISSUE TITLE
IndexError: string index out of range

### ISSUE THREAD

**Issue by wennzheng** [dingjiansw101/AerialDetection#40]
你好：
      我在自己的数据集上进行了训练，也生成了测试结果文件results.pkl。然而在使用parse_results.py进行分析的时候出现了下面问题。

Traceback (most recent call last):
  File "tools/parse_results.py", line 129, in <module>
    parse_results(config_file, pkl_file, output_path, type)
  File "tools/parse_results.py", line 67, in parse_results
    obb_results_dict = OBBDetComp4(dataset, outputs)
  File "/dat01/baijing/wenzheng/AerialDetection/mmdet/core/evaluation/dota_utils.py", line 188, in OBBDetComp4
    cls_name = dataset.CLASSES[label]
IndexError: string index out of range

请问有没有人遇到过，能不能帮我解释一下这个问题。

**Comment by BlackHandguy** [comment]
您好，请问您解决了吗？我也是这个问题。

**Comment by BlackHandguy** [comment]
> 你好：
> 我在自己的数据集上进行了训练，也生成了测试结果文件results.pkl。然而在使用parse_results.py进行分析的时候出现了下面问题。
> 
> Traceback (most recent call last):
> File "tools/parse_results.py", line 129, in
> parse_results(config_file, pkl_file, output_path, type)
> File "tools/parse_results.py", line 67, in parse_results
> obb_results_dict = OBBDetComp4(dataset, outputs)
> File "/dat01/baijing/wenzheng/AerialDetection/mmdet/core/evaluation/dota_utils.py", line 188, in OBBDetComp4
> cls_name = dataset.CLASSES[label]
> IndexError: string index out of range
> 
> 请问有没有人遇到过，能不能帮我解释一下这个问题。
您好，请问您解决了吗？我也是这个问题

**Comment by xiaobai824** [comment]
"""
Traceback (most recent call last):
  File "/home/data1_4t/baiyuxuan/anaconda3/envs/AerialDetection/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/data1_4t/baiyuxuan/anaconda3/envs/AerialDetection/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/data1_4t/baiyuxuan/AerialDetection/DOTA_devkit/ResultMerge_multi_process.py", line 177, in mergesingle
    x_y_2 = re.findall(r'\d+', x_y[0])
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tools/parseHJJ_results.py", line 129, in <module>
    parse_results(config_file, pkl_file, output_path, type)
  File "tools/parseHJJ_results.py", line 101, in parse_results
    os.path.join(dstpath, 'Task1_results_nms'), nms_type=r'py_cpu_nms_poly_fast', o_thresh=current_thresh)
  File "/home/data1_4t/baiyuxuan/AerialDetection/DOTA_devkit/ResultMerge_multi_process.py", line 232, in mergebypoly_multiprocess
    py_cpu_nms_poly_fast, o_thresh)
  File "/home/data1_4t/baiyuxuan/AerialDetection/DOTA_devkit/ResultMerge_multi_process.py", line 210, in mergebase_parallel
    pool.map(mergesingle_fn, filelist)
  File "/home/data1_4t/baiyuxuan/anaconda3/envs/AerialDetection/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/data1_4t/baiyuxuan/anaconda3/envs/AerialDetection/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
IndexError: list index out of range
我也是这个问题

**Comment by dingjiansw101** [comment]
Have you changed the categories in your new dataset class?

**Comment by ccl-1** [comment]
我也遇到了这个问题,类别修改过了.还有啥解决方法吗?

**Comment by wennzheng** [comment]
类别数是不需要加背景的（+1）

**Comment by flyingshan** [comment]
@wennzheng , you can try modifying the 'num_classes' parameter in the config file.

**Comment by heyun1994** [comment]
@xiaobai824 @wennzheng @BlackHandguy 
请问问题解决了吗？我也是这个问题
