### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by zhaojingru408** [dingjiansw101/AerialDetection#44]
where I run tools/test.py  ，I have the following problems：
    for i, data in enumerate(data_loader):
  File "/home/zjr/anaconda3/envs/AerialDetection/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/zjr/anaconda3/envs/AerialDetection/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AttributeError: Traceback (most recent call last):
  File "/home/zjr/anaconda3/envs/AerialDetection/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/zjr/anaconda3/envs/AerialDetection/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/media/sdc/zjr/code/AerialDetection/mmdet/datasets/custom.py", line 197, in __getitem__
    return self.prepare_test_img(idx)
  File "/media/sdc/zjr/code/AerialDetection/mmdet/datasets/custom.py", line 378, in prepare_test_img
    img, scale, False, proposal)
  File "/media/sdc/zjr/code/AerialDetection/mmdet/datasets/custom.py", line 332, in prepare_single
    img, scale, flip, keep_ratio=self.resize_keep_ratio)
  File "/media/sdc/zjr/code/AerialDetection/mmdet/datasets/transforms.py", line 33, in __call__
    img, scale_factor = mmcv.imrescale(img, scale, return_scale=True)
  File "/home/zjr/anaconda3/envs/AerialDetection/lib/python3.7/site-packages/mmcv/image/resize.py", line 132, in imrescale
    h, w = img.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'

I'm sure the image exists and no Chinese path.
If you have already identified the reason, you can provide the information here. Thanks

**Comment by s2016455** [comment]
Some problem. Have you solved it?
