### ISSUE TITLE
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by Miki-lin** [dingjiansw101/AerialDetection#45]
### I run the compile.sh with this step
Compile cuda extensions.
 ./compile.sh
### but it has some problem as following:

/media/miki/ubuntu/deep_learning/huoyan/AerialDetection-master/mmdet/ops/poly_nms/src/poly_nms_cuda.cpp:3:23: error: ‘AT_CHECK’ was not declared in this scope
 #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                       ^
/media/miki/ubuntu/deep_learning/huoyan/AerialDetection-master/mmdet/ops/poly_nms/src/poly_nms_cuda.cpp:8:5: note: in expansion of macro ‘CHECK_CUDA’
     CHECK_CUDA(dets);
     ^~~~~~~~~~
/media/miki/ubuntu/deep_learning/huoyan/AerialDetection-master/mmdet/ops/poly_nms/src/poly_nms_cuda.cpp:3:23: note: suggested alternative: ‘DCHECK’
 #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                       ^
/media/miki/ubuntu/deep_learning/huoyan/AerialDetection-master/mmdet/ops/poly_nms/src/poly_nms_cuda.cpp:8:5: note: in expansion of macro ‘CHECK_CUDA’
     CHECK_CUDA(dets);
     ^~~~~~~~~~
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/miki/anaconda/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1515, in _run_ninja_build
    env=env)
  File "/home/miki/anaconda/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 74, in <module>
    cmdclass={'build_ext': BuildExtension})
  File "/home/miki/anaconda/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/home/miki/anaconda/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/miki/anaconda/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/miki/anaconda/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/miki/anaconda/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/home/miki/anaconda/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/miki/anaconda/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 649, in build_extensions
    build_ext.build_extensions(self)
  File "/home/miki/anaconda/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/miki/anaconda/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/miki/anaconda/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 205, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/miki/anaconda/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/home/miki/anaconda/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 478, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/miki/anaconda/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1233, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/miki/anaconda/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1529, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension
Building cpu_nms...
running build_ext
skipping 'bbox.c' Cython extension (up-to-date)

my evironment as follow:
ubuntu18.04
Python 3.7.4
PyTorch 1.6.0
CUDA 10.2
NCCL 2.7.8
GCC 7.5
mmcv 1.1.5

**Comment by Elasine** [comment]
Same problem

**Comment by daibin88** [comment]
Same problem

**Comment by daibin88** [comment]
> ### I run the compile.sh with this step
> Compile cuda extensions.
> ./compile.sh
> 
> ### but it has some problem as following:
> /media/miki/ubuntu/deep_learning/huoyan/AerialDetection-master/mmdet/ops/poly_nms/src/poly_nms_cuda.cpp:3:23: error: ‘AT_CHECK’ was not declared in this scope
> #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
> ^
> /media/miki/ubuntu/deep_learning/huoyan/AerialDetection-master/mmdet/ops/poly_nms/src/poly_nms_cuda.cpp:8:5: note: in expansion of macro ‘CHECK_CUDA’
> CHECK_CUDA(dets);
> ^~~~~~~~~~
> /media/miki/ubuntu/deep_learning/huoyan/AerialDetection-master/mmdet/ops/poly_nms/src/poly_nms_cuda.cpp:3:23: note: suggested alternative: ‘DCHECK’
> #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
> ^
> /media/miki/ubuntu/deep_learning/huoyan/AerialDetection-master/mmdet/ops/poly_nms/src/poly_nms_cuda.cpp:8:5: note: in expansion of macro ‘CHECK_CUDA’
> CHECK_CUDA(dets);
> ^~~~~~~~~~
> ninja: build stopped: subcommand failed.
> Traceback (most recent call last):
> File "/home/miki/anaconda/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1515, in _run_ninja_build
> env=env)
> File "/home/miki/anaconda/lib/python3.7/subprocess.py", line 487, in run
> output=stdout, stderr=stderr)
> subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "setup.py", line 74, in
> cmdclass={'build_ext': BuildExtension})
> File "/home/miki/anaconda/lib/python3.7/site-packages/setuptools/**init**.py", line 145, in setup
> return distutils.core.setup(**attrs)
> File "/home/miki/anaconda/lib/python3.7/distutils/core.py", line 148, in setup
> dist.run_commands()
> File "/home/miki/anaconda/lib/python3.7/distutils/dist.py", line 966, in run_commands
> self.run_command(cmd)
> File "/home/miki/anaconda/lib/python3.7/distutils/dist.py", line 985, in run_command
> cmd_obj.run()
> File "/home/miki/anaconda/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 84, in run
> _build_ext.run(self)
> File "/home/miki/anaconda/lib/python3.7/distutils/command/build_ext.py", line 340, in run
> self.build_extensions()
> File "/home/miki/anaconda/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 649, in build_extensions
> build_ext.build_extensions(self)
> File "/home/miki/anaconda/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
> self._build_extensions_serial()
> File "/home/miki/anaconda/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
> self.build_extension(ext)
> File "/home/miki/anaconda/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 205, in build_extension
> _build_ext.build_extension(self, ext)
> File "/home/miki/anaconda/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
> depends=ext.depends)
> File "/home/miki/anaconda/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 478, in unix_wrap_ninja_compile
> with_cuda=with_cuda)
> File "/home/miki/anaconda/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1233, in _write_ninja_file_and_compile_objects
> error_prefix='Error compiling objects for extension')
> File "/home/miki/anaconda/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1529, in _run_ninja_build
> raise RuntimeError(message)
> RuntimeError: Error compiling objects for extension
> Building cpu_nms...
> running build_ext
> skipping 'bbox.c' Cython extension (up-to-date)
> 
> my evironment as follow:
> ubuntu18.04
> Python 3.7.4
> PyTorch 1.6.0
> CUDA 10.2
> NCCL 2.7.8
> GCC 7.5
> mmcv 1.1.5
> 
> ### however ,I can run mmdetection successfully in above evironment.

Hi,How to solve this issue?

**Comment by zhaw** [comment]
Solution:
replace all "AT_CHECK" with "TORCH_CHECK" in *_cuda.cpp files

**Comment by VissageMo** [comment]
> Solution:
> replace all "AT_CHECK" with "TORCH_CHECK" in *_cuda.cpp files

Helpful!

**Comment by SamMohel** [comment]
>  *_cuda.cpp

where can i find those file please ?

**Comment by susufancy** [comment]
> > *_cuda.cpp
> 
> where can i find those file please ?

in the file you run in command

**Comment by Anm-pinellia** [comment]
> Solution: replace all "AT_CHECK" with "TORCH_CHECK" in *_cuda.cpp files

nice method to solve this problem
