### ISSUE TITLE
ModuleNotFoundError: No module named 'mmdet.core.bbox.bbox'

### ISSUE THREAD

**Issue by xukaiyan** [dingjiansw101/AerialDetection#46]
Traceback (most recent call last):
  File "tools/train.py", line 7, in <module>
    from mmdet.datasets import get_dataset
  File "/home/lab716/xukaiyan/AerialDetection/mmdet/datasets/__init__.py", line 1, in <module>
    from .custom import CustomDataset
  File "/home/lab716/xukaiyan/AerialDetection/mmdet/datasets/custom.py", line 11, in <module>
    from .extra_aug import ExtraAugmentation
  File "/home/lab716/xukaiyan/AerialDetection/mmdet/datasets/extra_aug.py", line 5, in <module>
    from mmdet.core.evaluation.bbox_overlaps import bbox_overlaps
  File "/home/lab716/xukaiyan/AerialDetection/mmdet/core/__init__.py", line 1, in <module>
    from .anchor import *  # noqa: F401, F403
  File "/home/lab716/xukaiyan/AerialDetection/mmdet/core/anchor/__init__.py", line 2, in <module>
    from .anchor_target import anchor_target, anchor_inside_flags
  File "/home/lab716/xukaiyan/AerialDetection/mmdet/core/anchor/anchor_target.py", line 3, in <module>
    from ..bbox import assign_and_sample, build_assigner, PseudoSampler, bbox2delta
  File "/home/lab716/xukaiyan/AerialDetection/mmdet/core/bbox/__init__.py", line 1, in <module>
    from .bbox import bbox_overlaps_cython
ModuleNotFoundError: No module named 'mmdet.core.bbox.bbox'

What is the problem?

**Comment by imustwangxin** [comment]
me too !!!!!!! it's crazy

**Comment by tjmannn** [comment]
same problem, do you know how to modify anchor rotated angle?

**Comment by gewenchao** [comment]
有人解决了这个问题吗 分享一下

**Comment by lsq210** [comment]
same problem😭

**Comment by hjq052070** [comment]
同问，有人解决这个问题了吗？求分享

**Comment by imustwangxin** [comment]
好久之前做过的了，有点忘了，应该是建立一个__init__.py（可能本身就有）然后引入这个模块好像是这样

发自我的iPhone

**Comment by chandlerbing65nm** [comment]
Has anyone solved the problem?
