### ISSUE TITLE
训练错误 Expected object of scalar type Byte but got scalar type Bool for argument***

### ISSUE THREAD

**Issue by SueeH** [dingjiansw101/AerialDetection#48]
![image](https://user-images.githubusercontent.com/28698695/96429223-4a0e1100-1233-11eb-916d-b8292a3e0f53.png)
如截图所示，求问有遇到的么？
另：config中那么多配置文件，如何使用呢？

**Comment by SueeH** [comment]
错误信息如下：
python tools/train.py configs/DOTA/faster_rcnn_RoITrans_r50_fpn_1x_dota.py 
2020-10-19 17:25:35,670 - INFO - Distributed training: False
2020-10-19 17:25:36,255 - INFO - load model from: modelzoo://resnet50
/home/shj/env/miniconda3/envs/AerialDt/lib/python3.7/site-packages/mmcv/runner/checkpoint.py:145: UserWarning: The URL scheme of "modelzoo://" is deprecated, please use "torchvision://" instead
  warnings.warn('The URL scheme of "modelzoo://" is deprecated, please '
2020-10-19 17:25:36,491 - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
2020-10-19 17:25:39,197 - INFO - Start running, host: shj@senscape-X10DRG, work_dir: /home/shj/develop/yueguo/AerialDetection/work_dirs/faster_rcnn_RoITrans_r50_fpn_1x_dota
2020-10-19 17:25:39,197 - INFO - workflow: [('train', 1)], max: 12 epochs
Traceback (most recent call last):
  File "tools/train.py", line 95, in <module>
    main()
  File "tools/train.py", line 91, in main
    logger=logger)
  File "/home/shj/develop/yueguo/AerialDetection/mmdet/apis/train.py", line 61, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/home/shj/develop/yueguo/AerialDetection/mmdet/apis/train.py", line 197, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/shj/env/miniconda3/envs/AerialDt/lib/python3.7/site-packages/mmcv/runner/runner.py", line 359, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/shj/env/miniconda3/envs/AerialDt/lib/python3.7/site-packages/mmcv/runner/runner.py", line 263, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/home/shj/develop/yueguo/AerialDetection/mmdet/apis/train.py", line 39, in batch_processor
    losses = model(**data)
  File "/home/shj/env/miniconda3/envs/AerialDt/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/shj/env/miniconda3/envs/AerialDt/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/shj/env/miniconda3/envs/AerialDt/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/shj/develop/yueguo/AerialDetection/mmdet/models/detectors/base_new.py", line 95, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/home/shj/develop/yueguo/AerialDetection/mmdet/models/detectors/RoITransformer.py", line 142, in forward_train
    *rpn_loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
  File "/home/shj/develop/yueguo/AerialDetection/mmdet/models/anchor_heads/rpn_head.py", line 51, in loss
    gt_bboxes_ignore=gt_bboxes_ignore)
  File "/home/shj/develop/yueguo/AerialDetection/mmdet/models/anchor_heads/anchor_head.py", line 177, in loss
    sampling=self.sampling)
  File "/home/shj/develop/yueguo/AerialDetection/mmdet/core/anchor/anchor_target.py", line 63, in anchor_target
    unmap_outputs=unmap_outputs)
  File "/home/shj/develop/yueguo/AerialDetection/mmdet/core/utils/misc.py", line 24, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/home/shj/develop/yueguo/AerialDetection/mmdet/core/anchor/anchor_target.py", line 108, in anchor_target_single
    cfg.allowed_border)
  File "/home/shj/develop/yueguo/AerialDetection/mmdet/core/anchor/anchor_target.py", line 173, in anchor_inside_flags
    (flat_anchors[:, 2] < img_w + allowed_border) & \
RuntimeError: Expected object of scalar type Byte but got scalar type Bool for argument #2 'other' in call to _th_and

**Comment by SueeH** [comment]
pytorch版本问题，需要安装1.1 对应torchvision==0.3.0即可
