### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by kaikaizhu** [dingjiansw101/AerialDetection#6]
The following error occurred when I run demo_large_image.py.
Traceback (most recent call last):
  File "demo_large_image.py", line 1, in <module>
    from mmdet.apis import init_detector, inference_detector, show_result, draw_poly_detections
  File "/home/46211/Code/yaogan/AerialDetection/AerialDetection-master/mmdet/apis/__init__.py", line 2, in <module>
    from .train import train_detector
  File "/home/46211/Code/yaogan/AerialDetection/AerialDetection-master/mmdet/apis/train.py", line 10, in <module>
    from mmdet import datasets
  File "/home/46211/Code/yaogan/AerialDetection/AerialDetection-master/mmdet/datasets/__init__.py", line 1, in <module>
    from .custom import CustomDataset
  File "/home/46211/Code/yaogan/AerialDetection/AerialDetection-master/mmdet/datasets/custom.py", line 11, in <module>
    from .extra_aug import ExtraAugmentation
  File "/home/46211/Code/yaogan/AerialDetection/AerialDetection-master/mmdet/datasets/extra_aug.py", line 5, in <module>
    from mmdet.core.evaluation.bbox_overlaps import bbox_overlaps
  File "/home/46211/Code/yaogan/AerialDetection/AerialDetection-master/mmdet/core/__init__.py", line 1, in <module>
    from .anchor import *  # noqa: F401, F403
  File "/home/46211/Code/yaogan/AerialDetection/AerialDetection-master/mmdet/core/anchor/__init__.py", line 2, in <module>
    from .anchor_target import anchor_target, anchor_inside_flags
  File "/home/46211/Code/yaogan/AerialDetection/AerialDetection-master/mmdet/core/anchor/anchor_target.py", line 3, in <module>
    from ..bbox import assign_and_sample, build_assigner, PseudoSampler, bbox2delta
  File "/home/46211/Code/yaogan/AerialDetection/AerialDetection-master/mmdet/core/bbox/__init__.py", line 1, in <module>
    from .bbox import bbox_overlaps_cython
ImportError: dynamic module does not define module export function (PyInit_bbox)

**Comment by kaikaizhu** [comment]
I have slove this problem.

The following error occurred when I run ./compile.sh.
ImportError: No module named torch.utils.cpp_extension.

modify compile.sh
python =>  python3
