### ISSUE TITLE
执行prepare_dota1.py时报错，请问如何解决？

### ISSUE THREAD

**Issue by QCChou** [dingjiansw101/AerialDetection#7]
img name: P1452
img name: P0962
img name: P1838
img name: P1770
img name: P2220
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/zhouqc/anaconda3/envs/AerialDetection/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/zhouqc/anaconda3/envs/AerialDetection/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/zhouqc/project/objectDetection/AerialDetection/DOTA_devkit/SplitOnlyImage_multi_process.py", line 45, in SplitSingle
    assert np.shape(img) != ()
AssertionError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "prepare_dota1.py", line 102, in <module>
    prepare(srcpath, dstpath)
  File "prepare_dota1.py", line 93, in prepare
    split_test.splitdata(1)
  File "/home/zhouqc/project/objectDetection/AerialDetection/DOTA_devkit/SplitOnlyImage_multi_process.py", line 85, in splitdata
    self.pool.map(worker, imagenames)
  File "/home/zhouqc/anaconda3/envs/AerialDetection/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/zhouqc/anaconda3/envs/AerialDetection/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
AssertionError

在执行到P2220时，报出错误？请问是什么意思？怎么解决？

**Comment by 422301949** [comment]
I have the same problem, do you solved it?

**Comment by bao258456** [comment]
Sorry, I haven't this problem.

**Comment by hedes1992** [comment]
> img name: P1452
> img name: P0962
> img name: P1838
> img name: P1770
> img name: P2220
> multiprocessing.pool.RemoteTraceback:
> """
> Traceback (most recent call last):
> File "/home/zhouqc/anaconda3/envs/AerialDetection/lib/python3.7/multiprocessing/pool.py", line 121, in worker
> result = (True, func(*args, **kwds))
> File "/home/zhouqc/anaconda3/envs/AerialDetection/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
> return list(map(*args))
> File "/home/zhouqc/project/objectDetection/AerialDetection/DOTA_devkit/SplitOnlyImage_multi_process.py", line 45, in SplitSingle
> assert np.shape(img) != ()
> AssertionError
> """
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
> File "prepare_dota1.py", line 102, in
> prepare(srcpath, dstpath)
> File "prepare_dota1.py", line 93, in prepare
> split_test.splitdata(1)
> File "/home/zhouqc/project/objectDetection/AerialDetection/DOTA_devkit/SplitOnlyImage_multi_process.py", line 85, in splitdata
> self.pool.map(worker, imagenames)
> File "/home/zhouqc/anaconda3/envs/AerialDetection/lib/python3.7/multiprocessing/pool.py", line 268, in map
> return self._map_async(func, iterable, mapstar, chunksize).get()
> File "/home/zhouqc/anaconda3/envs/AerialDetection/lib/python3.7/multiprocessing/pool.py", line 657, in get
> raise self._value
> AssertionError
> 
> 在执行到P2220时，报出错误？请问是什么意思？怎么解决？

Hello, I met this question too.
I just check the original data(DOTA-v1.0), where 
train/images should **only contains** 1411 png file,  
val/images should **only contains** 458 png file,  
test/images should **only contains** 937 png file,  
the same number as the txt file in labelTxt. 

It seems when unzip the original zip file of images, there may leave other file which is not png

**Comment by ChengxiHAN** [comment]
> img name: P1452
> img name: P0962
> img name: P1838
> img name: P1770
> img name: P2220
> multiprocessing.pool.RemoteTraceback:
> """
> Traceback (most recent call last):
> File "/home/zhouqc/anaconda3/envs/AerialDetection/lib/python3.7/multiprocessing/pool.py", line 121, in worker
> result = (True, func(*args, **kwds))
> File "/home/zhouqc/anaconda3/envs/AerialDetection/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
> return list(map(*args))
> File "/home/zhouqc/project/objectDetection/AerialDetection/DOTA_devkit/SplitOnlyImage_multi_process.py", line 45, in SplitSingle
> assert np.shape(img) != ()
> AssertionError
> """
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
> File "prepare_dota1.py", line 102, in
> prepare(srcpath, dstpath)
> File "prepare_dota1.py", line 93, in prepare
> split_test.splitdata(1)
> File "/home/zhouqc/project/objectDetection/AerialDetection/DOTA_devkit/SplitOnlyImage_multi_process.py", line 85, in splitdata
> self.pool.map(worker, imagenames)
> File "/home/zhouqc/anaconda3/envs/AerialDetection/lib/python3.7/multiprocessing/pool.py", line 268, in map
> return self._map_async(func, iterable, mapstar, chunksize).get()
> File "/home/zhouqc/anaconda3/envs/AerialDetection/lib/python3.7/multiprocessing/pool.py", line 657, in get
> raise self._value
> AssertionError
> 
> 在执行到P2220时，报出错误？请问是什么意思？怎么解决？

请问你解决这个问题了么？谢谢

**Comment by ChengxiHAN** [comment]
> I have the same problem, do you solved it?

请问你解决这个问题了么？谢谢

**Comment by hedes1992** [comment]
> > I have the same problem, do you solved it?
> 
> 请问你解决这个问题了么？谢谢

I just check the img's number and delete the file which are not png files

**Comment by StuLiu** [comment]
数据集图片文件的后缀要与SplitOnlyImage_multi_process.splitbase类的参数‘ext’保持一致。
![image](https://user-images.githubusercontent.com/19245323/119128754-a0ad2900-ba68-11eb-9bbf-05639c0fa781.png)
